### ISSUE TITLE
CoffeeCup

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#1]
Replace CoffeeKup with CoffeeCup?

**Comment by Mpdreamz** [comment]
+1, it be nice if the whole ecosystem moved forward. Just forked this repo and doing an npm install from the clone worked perfect. Thanks!

**Comment by edubkendo** [comment]
+1 as well. Just seems to make sense.

**Comment by Hypee** [comment]
+1, the CoffeeCup team is doing a great work.

**Comment by scien** [comment]
+1 https://github.com/gradus/coffeecup
