### ISSUE TITLE
Handlebars Support / registering view engines

### ISSUE THREAD

**Issue by rmetzler** [zappajs/zappajs#10]
I couldn't figure out how to register another view engine in my app code, so I added `hbs` in `package.json`

https://github.com/rmetzler/zappajs/tree/handlebars-support

I'm not sure if this is worth a pull request or I just overlooked the register function.

**Comment by shimaore** [comment]
I suspect the solution should look something like:

```
@register hbs: @zappa.adapter('hbs')
```

modelled after

```
@register jade: @zappa.adapter('jade')
```

in `test/views.coffee`.
