### ISSUE TITLE
@include does not work inside @client

### ISSUE THREAD

**Issue by ramstein74** [zappajs/zappajs#103]
my app.coffee in the root folder where my server.coffee resides

@include = ->
  console.log 'include '

my server.coffee

 @client '/a.js': -> 
    @include './app'
@view index: ->
  doctype 5
  html ->
    head ->
      script src: '/zappa/Zappa-simple.js'
  "stylesheet"
      script src: '/a.js'

When i browse to my server i get the error in my scripts\a.js
;zappa.run(function () {
        return this.include('./app');
Uncaught TypeError: undefined is not a function
      });

**Comment by shimaore** [comment]
You should split it as:

```
@include = ->
  @client '/a.js': ->
    console.log 'include '
```

**Comment by ramstein74** [comment]
To clarify my need 
I have a lot of code to place inside @client '/app.js' :->
So i think its cleaner to separate the client code in another file
That is why i´m trying to use @include inside @client 

i dont understand your suggestion
it does not work either...

@include shoud be beneath @client and not the other way right?

i noticed that @include works outside @client but not inside

Thank you

**Comment by shimaore** [comment]
Sorry for the delay @ramstein74 
What I meant is that you should do:

```
# main.coffee
zappajs ->
  @include 'app'
  @view 'index': ->
     # etc.
```

Then in `app.coffe`:

```
@include = ->
  @client 'a.js', ->
    # your code here
```

The `@include` command is only available at the root of the zappa application.

**Comment by ramstein74** [comment]
Great!!! it works
thank you
