### ISSUE TITLE
@include does not work under @client

### ISSUE THREAD

**Issue by ramstein74** [zappajs/zappajs#104]
i cannot get @include to work inside @client

my /static/app.coffee
@include = ->
  console.log 'app here'

in my server code
  @client '/a.js': ->
    @include './static/app'

however if i move the line 
    @include './static/app' outside it logs in my server code
"app here"

so is it possible to have @include working inside @client ?

**Comment by shimaore** [comment]
`@include` is only available at the top level. Try `require` inside `@client`.

**Comment by ramstein74** [comment]
using require  inside @client for ex.
<code>
  @client '/app1.js': ->
    require('./static/app.coffee') ->
      console.log(myfunc1)
</code>
i get 
Uncaught ReferenceError: require is not defined
