### ISSUE TITLE
ZappaJS 1.1 and Express 4 Usage Questions

### ISSUE THREAD

**Issue by fgruner** [zappajs/zappajs#108]
Hello,

Trying to port over to 1.1 from the changes that I made to add express 4. I have a question about @use..

In order to get the body-parser working, I had added the following in zappa:

bodyParser = require 'body-parser'
bodyParser: ->
  bodyParser.json()
  bodyParser.urlencoded extended:yes
legacyBodyParser:bodyParser extended:yes

The bodyParser portion got rid of the express error for deprecated middleware, but didn't process a lot of the forms correctly for me and I couldn't figure out why, but when I used the added the legacyBodyParser line shown above, it had no express error and processed my forms correctly.

Now with zappajs 1.1, I'm trying the following:

@use 'body-parser': extended:yes

And I'm getting the express deprecated middleware error. With zappajs 1.1, how can I duplicate what I had working above for legacyBodyParser?  Also, any ideas why the new bodyparser replacement doesn't seem to replace the old one?

Thanks,

Fred

**Comment by fgruner** [comment]
Got this to work from one of the examples:

@use (require 'body-parser').urlencoded extended:true

**Comment by fgruner** [comment]
One more question.. Express 4 has a new router, and I'm wondering how to get at the features through zappa.

I want to be able to do things like app.all (where I setup middleware for certain paths), or setup a router for specific paths and do a router.all with the middleware.

Should I use @app.all?

Are you planning on building and zappa shortcuts to the new router middleware?

Fred

**Comment by shimaore** [comment]
Fred,

## @use

To answer your fist question, as you figured out the Express 4 way to do it is:

```
zappa = require 'zappajs'
zappa ->

  @use (require 'body-parser').json()
  @use (require 'body-parser').urlencoded extended:yes

  @post '/': ->
    @json @body
```

This allows support for both formats, testing:

```
curl -X POST -d '{"foo":3}' -H 'Content-Type: application/json' http://127.0.0.1:3000/
-> {"foo":3}
curl -X POST -d 'foo=3' -H 'Content-Type: application/x-www-form-urlencoded' http://127.0.0.1:3000/
-> {"foo":3}
```

## @all 

Regarding `@app.all` a shortcut has been provided in ZappaJS for a while, feel free to use `@all` :)

## Middleware in unexpected places

There's a new `@wrap` (root scope) command in ZappaJS 1.x which allows you to wrap any middleware "the Zappa way" in case you want to use them with unsupported operations, I guess something like

```
router.all @wrap ->
  @locals.user = @session.user
  # etc. Your Code Here :)
```

will do what you want?
