### ISSUE TITLE
The sample code does not work

### ISSUE THREAD

**Issue by ramstein74** [zappajs/zappajs#109]
the sample code at
https://github.com/zappajs/zappajs
below sinopsis

does not work
first i got error on this line and i removed it
{doctype,html,head,script,body,div} = @teacup
there is no info about @teacup or @coffee in the api

then still this error
GET http://127.0.0.1:3000/zappa/simple.js  127.0.0.1/:1
Uncaught ReferenceError: zappa is not defined client.js:1

**Comment by shimaore** [comment]
@ramstein74 Could you provide more details? I copy & pasted the code, tested with Firefox and ZappaJS 1.1 and things worked. What steps did you follow, which version of ZappaJS are you testing with, & what client?

**Comment by ramstein74** [comment]
Seems i have upgraded zappa with

npm install -g zappajs@1.x but still using zappa 0.4.22

how do i change to use the new zappa?

2014-09-15 14:41 GMT+01:00 Stéphane Alnet notifications@github.com:

**Comment by shimaore** [comment]
Oh my, did I forget to reply to your followup? I'm sorry. I would assume the issue had to do with zappajs in local directory vs global zappajs (i.e. `npm install` vs `npm -g install`).
