### ISSUE TITLE
Support Route Middleware

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#11]
to make this work:

``` coffee
@get '/', ->
            @next()
        , ->
            log "lol you'll never get here"
            @response.end()
```

**Comment by scien** [comment]
+1.  Might be more clear to change "Support Several Routes" to "Support Route Middleware"

the example use case from express look likes...
http://expressjs.com/guide.html#route-middleware

app.get('/user/:id', function(req, res, next){
  loadUser(req.params.id, function(err, user){
    if (err) return next(err);
    res.send('Viewing user ' + user.name);
  });
});

function loadUser(req, res, next) {
  // You would fetch your user from the db
  var user = users[req.params.id];
  if (user) {
    req.user = user;
    next();
  } else {
    next(new Error('Failed to load user ' + req.params.id));
  }
}

app.get('/user/:id', loadUser, function(req, res){
  res.send('Viewing user ' + req.user.name);
});

**Comment by Radagaisus** [comment]
A quick fix for now:

``` coffee
    # No magic here
    @app.get '/', (req, res, next) ->
            next()
        , (req, res) ->
            res.write('bla bla bla')
            res.end()
```

**Comment by shimaore** [comment]
There was already a proposal to do so in mauricemach/zappa#104 however (see #8) it conflicts with 24e626c43752e3789bedf0beaeec100b1103c682 and might conflict with mauricemach/zappa#100

**Comment by shimaore** [comment]
Recent versions of Node have `util.isRegExp` etc. so we should be able to do things properly. We need to come up with an unambiguous, updated specification for the parameters to the `get`, `post`, ... methods that supports what zappa does today and can also handle middleware.

**Comment by Radagaisus** [comment]
``` coffee
@get /regex/,
  ->
    'hi' + @request.stuff
  ->
    'sup'

@get
  '/': [
     -> 'boo'
     -> 'daa'
     ]
  '/wiki': 'wiki'
  '/chat': -> response.send 'chat'
```

How about this? I think the latter (object) form of this function is rather used. The first part looks really ok syntax wise.

**Comment by shimaore** [comment]
Slightly modified version of the fix proposed by @grncdr in zappa.

This still needs documentation.

Also: as this is, the middleware is executed in a regular connect/express (req,res,next) context instead of a Zappa context, so with the above patch one writes:

```
@get '/',
  (req, res, next) ->
    next()
  ->
    @send 'bla bla bla'
```

Before we release a new version of zappajs we need to decide whether we want the middleware to use the Connect/Express conventions, or whether we want to have Zappa-style route middleware (since it'll be impossible to change once people start using it).

**Comment by Radagaisus** [comment]
I think the whole point is being able to use `@request`, et. al. Otherwise I can just write the regular `@app.get # ...`.
