### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by dlemper** [zappajs/zappajs#110]
Hi, this one is more a question than an issue:
In version 0.5 there was a default layout. After switching from 0.5 to 1.2, the default layout is not getting loaded anymore. Is that feature removed from zappa or do I have to change anything to get that one working again?
In 0.5 I just changed the default layout by adding a layout view like this:
`@view 'layout': ->`

**Comment by shimaore** [comment]
Hi Daniel,
You're correct, layout is no longer in 1.x, due to the removal of partials in Express 3 (and 4).
You can still find [the definition of the old `default layout`](https://github.com/zappajs/zappajs/blob/0.x/src/zappa.coffee#L653) for reference. In [`teacup`](http://goodeggs.github.io/teacup/) you could use something like `body require body_module`to simulate partials, I suppose.

**Comment by dlemper** [comment]
Hi Stéphane,
thanks for clarifying the current situation!
Do you mean a teacup helper as the partials replacement? (as described here: https://github.com/goodeggs/teacup#helpers) That seems to be feasible..

**Comment by shimaore** [comment]
Hi Daniel,
Yes, that's exactly what I had in mind! :)

**Comment by dlemper** [comment]
Hi Stéphane,
sorry I didn't have the time to answer in the meantime..
Do you think it would be possible to add a `@layout` function to zappa in order to create an alternative to partials?
I imagined it like this:

```
@layout 'default':
  doctype 5
  html
    head
    ...
    body @content
```

And then in the view:

```
@view 'index'
  @layout 'default', () ->
    p 'Hello, World!'
```

Sorry if that looks awkward and isn't really compilable.. I'm quite new to coffeescript and zappajs ;-)
However, if the idea is possible to code and you think it's worth it, I'd try implement it in a fork of zappajs.

**Comment by shimaore** [comment]
Hi Daniel,
You could make it a regular function:

```
Zappa = require 'zappajs'
Zappa ->
  {doctype,html,head,title,script,body,div,form,input,button} = @teacup
  layout = (content) ->
    doctype 5
    html ->
      head ->
        title 'PicoChat!'
        script src: '/zappa/simple.js'
        script src: '/index.js'
      body content

  @view index: ->
    layout ->
      div id: 'panel'
      form ->
        input id: 'box'
        button 'Send'

  @get '/', ->
    @render 'index'
```

Using teacup there is no magic involved in the views anymore, so this kind of things are now possible.

**Comment by dlemper** [comment]
Hi Stéphane,
wow that's great and simple! Thanks a lot! :)

**Comment by dlemper** [comment]
Hi Stéphane,
sorry to reopen this issue, but I tried out your `require` approach from your first answer (which is quite better for my project) and it doesn't work.. However I'm not sure if I did it right :-/
I use your example from your last answer to demonstrate of what I did:
file 'app.coffee':

```
Zappa = require 'zappajs'
Zappa ->
  {doctype,html,head,title,script,body} = @teacup
  @view index: ->
    {layout} = require './layout'
    layout ->
      div id: 'panel'
      form ->
        input id: 'box'
        button 'Send'

  @get '/', ->
    @render 'index'
```

file 'layout.coffee':

```
{doctype,html,head,title,script,body,renderable} = require 'teacup'

module.expports =
  layout: renderable ({content}) ->
    doctype 5
    html ->
      head ->
        title 'PicoChat!'
        script src: '/zappa/simple.js'
        script src: '/index.js'
      body content
```

Using these scripts, the browser doesn't render anything.. :(
Did I do something wrong?

**Comment by shimaore** [comment]
Hi Daniel,

I spotted a typo in `expports` ;) but even when correcting this and adjusting for proper function calls, there is an issue arising from the fact that the `teacup` objects used in the view and the layout are not the same, and this causes buffering issues (I was able to render the inner content but not the layout). Here's a working version that works around that last problem (which isn't documented as far as I can tell in the teacup examples, maybe this is specific to the way Express or Zappa do things):

[app.coffee]

```
Zappa = require 'zappajs'
Zappa ->
  {doctype,html,head,title,script,body,div,form,input,button} = @teacup
  {layout} = (require './layout') @teacup

  @view index: ->
    layout ->
      div id: 'panel'
      form ->
        input id: 'box'
        button 'Send'

  @get '/', ->
    @render 'index'
```

[layout.coffee]

```
module.exports = (teacup) ->
  layout: (content) ->
    {doctype,html,head,title,script,body,div,form,input,button} = teacup
    doctype 5
    html ->
      head ->
        title 'PicoChat!'
        script src: '/zappa/simple.js'
        script src: '/index.js'
      body content
```

**Comment by dlemper** [comment]
Hi Stéphane,
thank you once again! Your example works perfectly! (Now this one really gets closed ;) )
However I have troubles doing this in my application, that I'm porting from zappajs 0.5 to 1.2.. Only the layout gets rendered on request but not the content and I'm sure there's no typo this time ;) Do you have a suggestion for a debugger or an idea on how I can catch the bug?

**Comment by shimaore** [comment]
@dlemper I generally use `console.log` to make sure the parameters are there and the code runs through the proper steps. Adding a `console.log content` right before the line that says `body content` should give you a decent start? :)

**Comment by dlemper** [comment]
@shimaore OK, that's how I do it, too ;) I tried out node-inspector, but it didn't work as I expected...
