### ISSUE TITLE
The sample code doesn't work — again

### ISSUE THREAD

**Issue by punund** [zappajs/zappajs#112]
What I did was

```
npm init
npm i zappajs --save #  "zappajs": "^3.0.0"
cat > server.js # sample from README

coffee server.coffee
```

Starts up ok, go to `http://localhost:3000`, and boom,

```
Uncaught ReferenceError: zappa is not defined
```

in browser console.

**Comment by shimaore** [comment]
Sorry about this; I haven't gotten to testing the client-side as part of the build. This should work now; make sure to also update the example source to load the proper bundle.

**Comment by shimaore** [comment]
(This is patched in 3.0.1.)

**Comment by punund** [comment]
:+1:

**Comment by punund** [comment]
Now I am getting 

```
GET http://localhost:3443/zappa/socket/__local/6BuKmnEvnhrLD6pMAAAC 500 (Internal Server Error)
```

The offending line is

```
xhr.send( options.hasContent && options.data || null );
```

within jquery.

UPDATE: this has to do with session_store, https://github.com/zappajs/zappajs/blob/3.x/src/zappa.coffee#L584

**Comment by shimaore** [comment]
This would only happen if you set `zappa_prefix` in your application, judging by the port maybe it's missing an `s` in `https`? (Also please open a new issue on github for new problems so that I can reference it explicitly if I need to do a change in the code!)
