### ISSUE TITLE
Sample code requires session

### ISSUE THREAD

**Issue by punund** [zappajs/zappajs#113]
(carried over from #112)
Now I am getting

```
GET http://localhost:300/zappa/socket/__local/6BuKmnEvnhrLD6pMAAAC 500 (Internal Server Error)
```

in the console.  No `zappa_prefix`, copy-pasted sample from README.  It seems that it insists on having sessions configured:

https://github.com/zappajs/zappajs/blob/3.x/src/zappa.coffee#L584

**Comment by shimaore** [comment]
Normally the 500 error should not prevent the client-side code from progressing. It should be caught inside the `.fail` section of the `$.getJSON` call inside `@share`.

If no session-store is present the only thing that should be missing is the ability to use [`@session`](http://zappajs.github.io/zappajs/docs/reference#session-2) from a socket.io event handler (in other words, inside `@on`, server-side). All over features should be available. (Obviously interested in any report of things working differently!!)

**Comment by shimaore** [comment]
@punund Thank you for your thorough testing BTW!

**Comment by shimaore** [comment]
This is now (4.x) properly handled (in zappajs-client); on the server-side if no session is present then no `@session` object is provided.
