### ISSUE TITLE
@client without "zappa.run"

### ISSUE THREAD

**Issue by punund** [zappajs/zappajs#115]
Would it be feasible to add an option to the `@client` method in the root scope so that no `zappa.run` wrapper is added?

**Comment by shimaore** [comment]
Are you looking for `@coffee` maybe?

**Comment by punund** [comment]
As per documentation, `@coffee` serves `;#{coffeescript_helpers}(#{your_function})()`" as `/foo.js`, with content-type `application/javascript`.

However, there is no documentation for `coffescript_helpers`, and while trying

```
@coffee '/hi.js', ->
   alert 'hi'
```

and including script /hi.js, I don't get anything.

`/hi.js` serves this: https://gist.github.com/punund/c0a7ec7ba640a9553c37

I suspect that there should be `};})()();` and not `};})();` at the end

What I am trying to do is to serve just plain compiled coffescript, no wrappers and no helpers.

**Comment by shimaore** [comment]
One needs to wrap coffeescript in some ways because the coffeescript compiler relies on helper functions in the generated code. However that's what `@coffee` is supposed to do, so this looks like a bug.

**Comment by shimaore** [comment]
This should be fixed in v3.2.0.
