### ISSUE TITLE
Support listening on IPC socket

### ISSUE THREAD

**Issue by atifaziz** [zappajs/zappajs#116]
Express and Node support [listening on a Unix domain socket (or named pipes in Windows)](https://nodejs.org/api/http.html#http_server_listen_path_callback) for IPC but Zappa allows the more traditional host plus port combination only. It could be easily fixed to allow use of IPC sockets, and in fact, [it almost does](https://github.com/zappajs/zappajs/blame/2e6c1bd024af532d123d7f4dd729ee7a1c93cce3/src/zappa.coffee.md#L868-L871):

``` coffee
      if host
        server.listen port, host
      else
        server.listen port
```

The problem is that `port` is always assumed to be numeric (and also [initialized to 3000 as a default](https://github.com/zappajs/zappajs/blame/2e6c1bd024af532d123d7f4dd729ee7a1c93cce3/src/zappa.coffee.md#L839)) & I think that's because `zappa.run` allows the host and port to be specified _in any order_:

> `zappa.run [host,] [port,] [{options},] root_function`
> 
> Takes a function and runs it as a zappa app. Optionally accepts a port number, and/or a hostname (any order). The hostname must be a string, and the port number must be castable as a number.

`server.listen` internally relies on the fact that [if its first argument is a string then it's the path of the IPC socket](https://github.com/nodejs/node/blob/master/lib/net.js#L1375-L1379) otherwise a TCP/IP port number:

``` js
    // ...
  } else if (isPipeName(arguments[0])) {
    // UNIX socket or Windows pipe.
    const pipeName = self._pipeName = arguments[0];
    listen(self, pipeName, -1, -1, backlog);

  } else // ...
```

[`isPipeName`](https://github.com/nodejs/node/blob/master/lib/net.js#L41-L43) is simply defined as:

``` js
function isPipeName(s) {
  return typeof s === 'string' && toNumber(s) === false;
}
```

I see two resolutions:
1. Don't allow `host` and `port` arguments to be supplied in any order. & then use the same discrimination logic as `server.listen`.
2. Allow `options` object argument to allow IPC socket specification via a `path` property (just as it already permits `host` and `port` today) that is then passed on to `server.listen`.

Given that 1 will introduce a breaking change, I'm guessing 2 is safer and more desirable. Happy to submit a PR for 2 if reasonable.

**Comment by shimaore** [comment]
> Given that 1 will introduce a breaking change, I'm guessing 2 is safer and more desirable. Happy to submit a PR for 2 if reasonable.

Yes, most definitely appreciated if you'd like to! :)

**Comment by shimaore** [comment]
Looking at the existing code, the simplest way would be to make `path` a synonym for `port`. In other words this works with:

```
(require 'zappajs') port:"/ipc_path", ->
```

However maybe when we do configuration with a string, we could detect that the string starts with a '/' (or a '\') and then assume it's an IPC path?

**Comment by shimaore** [comment]
Hmm autodetection won't work, the path maybe a relative path. There's no way to know whether

```
 (require 'zappajs') 'bear', ->
```

means `bear` is a hostname or an IPC path.

**Comment by atifaziz** [comment]
@shimaore Yeah, that's the problem indeed. For purpose of clarity, I just kept it as a separate property. I think the whole idea of allowing host or port in any order does complicate the cases. I was about open a PR for review or would you rather just continue the dialogue here? Also looking for advice on how you want to test this.

**Comment by shimaore** [comment]
@atifaziz PR sounds good, I think we've got the idea down. I was trying to find a clever way to do this but there isn't.
For tests I think a simple `get` test in `tests/run.coffee` should be enough?

**Comment by shimaore** [comment]
This is in ZappaJS 5.2.0.
