### ISSUE TITLE
Make Socket.io optional

### ISSUE THREAD

**Issue by scien** [zappajs/zappajs#12]
Thoughts? Is there a better way to implement this?

https://github.com/scien/zappajs/commit/4ee71980801a03cbac699a75f275537afb37e46f

**Comment by scien** [comment]
example use would be...
require ('zappa') {
  port: 3000
  use_io: false
}, ->

**Comment by shimaore** [comment]
Two suggestions:
- Write:
  
  ```
  io?.sockets.on 'connection', (socket) ->
  ```
  
  instead of 
  
  ```
    if zappa.use_io
      io.sockets.on 'connection', (socket) ->
  ```
  
  in order to get a _much_ shorter diff.
- Use a positive to indicate a change from defaults, so `disable_io` instead of `use_io`.
