### ISSUE TITLE
Integrate `forever`

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#17]
[suggested by @scien]
integrate forever so you could do something like

```
require('zappa').daemon 3000, ->
```

or

```
{@app} = require('./zappa'),
@app.daemonize 'log.txt', 'error.txt'
```

**Comment by scien** [comment]
people may want to apply any number of arguments (max, logfile, outfile, errfile, path, append, pidfile, minuptime, debug, verbose, watch, etc.).  might be good to make the argument a dictionary of input options.

```
@app.daemonize {logfile: '/path/to/log.txt', append: true}
```

**Comment by shimaore** [comment]
Some thoughts after researching this a little:
- I wonder what kind of issues [forever-webui](https://github.com/FGRibreau/forever-webui) ran into that made them switch to `supervisord` from `forever`?
- I'm not sure we can actually start `forever` that way -- the documentation and examples have a script file name as the argument. I doesn't look like you can `forever` a function.
- Do we want to tie Zappa to one solution? (The npm registry points to `immortal`, `node-watchdog`, .. FWIW I use [daemon(3)](http://www.libslack.org/daemon/) from within `package.json` so that I can `npm start`/`npm stop` my Zappa apps)

Maybe the best approach would be to include some kind of `forever` wrapper in the examples?

**Comment by Hypee** [comment]
If it can be useful to anybody searching for the way to launch a ZappaJS application with "forever", here is a code example :

app.coffee :

``` coffeescript
zappa_app = ->
  @get "/" :
    "Zappa rocks !"

my_server = require('zappajs').app( zappa_app, {disable_io: true, require_css: []} )

port = process.env.PORT or 3000
my_server.app.listen( port )
```

Then start the instance with :

``` bash
PORT=80 NODE_ENV=production forever start -c coffee app.coffee
```

**Comment by scien** [comment]
new module makes this possible.

https://github.com/nodejitsu/forever-monitor

**Comment by scien** [comment]
scratch that. forever-monitor doesn't work as I expected. I moved the logic to package.json and it's been great though.  let's just document the two proposed solutions here. no need to integrate anything special into zappa.

```
{
  "name": "app",
  "config": {
    "port": 3000
  },
  "scripts": {
    "start": "npm stop; forever start -a -l /u/log/project/forever.log -o /u/log/project/output.log -e /u/log/project/error.log -c coffee app.coffee",
    "restart": "forever restart app.coffee",
    "stop": "forever stop app.coffee"
  }
}
```

then manage the service with...

```
npm start
npm restart
npm stop
```

Then I have my post-receive script on production to call npm restart after deploy.

I'm also planning on playing around with https://github.com/learnboost/cluster as some point.  I'll submit an example if I get around to it.  Has anybody else used cluster before?

**Comment by shimaore** [comment]
Yup, good idea to document ways to do this. I currently use [daemon(1)](http://www.libslack.org/daemon/) for the same purpose, `package.json` looks like:

```
...
  "scripts": {
    "start": "daemon -n app.coffee -o daemon.debug -r -D \"`pwd`\" -- coffee ./app.coffee",
    "stop": "daemon -n app.coffee -o daemon.debug --stop"
  }
```

I guess `forever` would run anywhere Node.js runs though, so it doesn't create extraneous external dependencies.

Regarding `cluster`, is it the same as [`cluster`](http://nodejs.org/api/cluster.html) in recent Node.js? If not, the name-clash is unlucky.

**Comment by scien** [comment]
interesting. separate modules. Looks like it collided at node v0.5.10 when the native module was introduced.  learnboost hasn't updated in 7 months, so I guess they switched over.  other people maintain the old project at https://github.com/ql-io/cluster2

ref: https://github.com/LearnBoost/cluster/issues/168

**Comment by scien** [comment]
the long "start" line was bugging me, so now my package.json looks like

```
  "start": "cake start",
  "restart": "cake restart",
  "stop": "cake stop"
```

**Comment by scien** [comment]
Note: be careful with npm restart until this issue is closed - https://github.com/isaacs/npm/pull/2716

**Comment by Radagaisus** [comment]
I don't think this is a good opinion for Zappa to hold. There's a lot of solutions for daemonizing besides forever, none of them is clearly the best option. For example, I use monit and cluster on production and nodemon locally.

I think a simpler solution for this need is a small cake file that will help people to kickstart development with zappa. Basically all developers needs this two tasks:
1. quickly compile everything, maybe add a `lib` and `dist` folders convention.
2. something like `nodemon server` or `forever whatever`. Maybe add a small bin for zappa, just like express has?

**Comment by shimaore** [comment]
@Radagaisus at this point I don't think anyone is advocating to do this anymore -- we're mostly tracking solutions, these should be added either to the documentation or to the examples. (Looking for volunteers!)

However regarding kickstarting development I agree we should have (probably in a separate repository under https://github.com/zappajs ) a demo/template, so that newcomers can do:

```
git clone git://github.com/zappajs/zappa-start.git
npm install
npm start
```

and have a nice-looking template, all important dependencies in place in `package.json` (connect-assets, zappajs-partials, gzippo, ..), sensible defaults for development (watch #9) and production (cluster,  ...), maybe some plugins (`@include`) for common tasks (e.g. from zappajs' `examples/` or from stuff people would contribute), etc.

Maybe we can come up with a better name than `zappa-start`, but I agree, let's get this done.

**Comment by shimaore** [comment]
OK, I'm closing this issue against zappajs, please contribute code to [zappajs/zappajs-template](https://github.com/zappajs/zappajs-template) !
