### ISSUE TITLE
Better integrated client-side templating

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#18]
[suggested by @scien]

> Right now my run script compiles, combines, and minifies my coffeecup templates, then i just serve the file up in a static dir. Would be nice to be able to just host these from a `@client`.
> To assist with this, `@include` might be a nice feature inside `@client`. Currently if i want to organize my code in multiple files, i'd have to serve them from different urls.

**Comment by scien** [comment]
I think just allowing @include within @client would solve the problem.  @include meaning take the coffeescript from the new file and insert it as if i wrote the code in this place.  To further simplify, you could include a directory and it would insert everything under it.  so in my case i would have all my client code under /app/client/. then i would have a @client '/js/app.js', -> @include './path/to/app/client'

for extra reference here's my current compile script

```
#!/bin/bash
sources[0]="init"
sources[1]="helpers"
sources[2]="templates/*/*"
sources[3]="views/*/*"
sources[4]="router"
sources[5]="main"
cnt=${#sources[@]}
for ((i=0;i<cnt;i++)); do
    sources[$i]="app/client/$(sources[$i]}.coffee"
done
coffee -cj public/js/apps.js ${sources[@]}
uglifyjs -o public/js/app.js public/js/app.js
```

since ordering matters in this case, my new code would look like

```
@client '/js/app.js': ->
    @include 'app/client/init'
    @include 'app/client/helpers'
    @include 'app/client/templates'
    @include 'app/client/views'
    @include 'app/client/router'
    @include 'app/client/main'
```

**Comment by shimaore** [comment]
If I understand properly it looks like we need something like `requirejs` and a new method, for example:

```
@package '/js/app.js': [
    'app/client/init'
    'app/client/helpers'
    'app/client/templates'
    'app/client/views'
    'app/client/router'
    'app/client/main'
]
```

**Comment by scien** [comment]
that'd work for me.  I can't think of any use cases that wouldn't solve.

As a side note, one thing I've found useful is being able to recompile this resource without having to restart the server.  it'd be great to have "watch" work with this and recompile as needed when any of the files are updated.

**Comment by shimaore** [comment]
I looked a little bit more into this:
- It seems that [connect-assets](https://github.com/TrevorBurnham/connect-assets) can do most of what is needed. So we should recommend it if only static files are involved.
- Additionally we implement a new `@include` function inside the query context. This `@include` accepts an array of URL paths.
  - `@include` will query the Zappa routes, doing (the equivalent of) a `GET` on each path, and return the concatenated contents. This way you can combine the outputs of `@client`, `@shared`, `@coffee`, `@js`, and static JS files to build a new `@js` route; or combine the outputs of `@css`, `@stylus`, `@less`, ... and static CSS files to build a new `@css` route; or maybe even combine HTML/Jade/... fragments (static or dynamic) into a single `@get` HTML document.
  - By default the content is rebuilt each time `@include` is called; for production we could add a `@enable` option to memoize `@include` (combine with Zappa's `minify` setting for optimal output). (We might also provide a per-`@include` option to prevent memoization on a case-by-case basis. Is that necessary?)

[edit] Remove example for syntax -- this has to be done async, will publish syntax once code is written!

**Comment by shimaore** [comment]
2ffb39eb8df52d8ee60bfa9099d6b569c663d36a (in `route-include` branch) does the base job but is very ad-hoc (and would break with non-utf8 encodings).

The syntax is:

```
@get '/js/app.js': ->
  @include [
    '/js/foo.js'
    '/js/bar.js'
  ]
```

Is it worth pursuing? With connect-assets' `#= require` this seems kind of superfluous.

**Comment by scien** [comment]
connect-assets/snockets looks really promising.  i'll try it out later this week.  at first glance, it looks like we could do the following. have you used connect-assets before?

```
@use 'connect-assets', {build: true}
@get '/js/app.js': ->
    #= require 'app/client/init'
    #= require_tree 'app/client/helpers'
    #= require_tree 'app/client/templates'
    #= require_tree 'app/client/views'
    #= require 'app/client/router'
    #= require 'app/client/main'
```

**Comment by shimaore** [comment]
FWIW this has been discussed at length in mauricemach/zappa#94 and other, older issues.

Essentially there are lots of solutions for static assets. I think I'll stick to mauricemach's position and avoid any specific integration. [edit] This doesn't prevent us from documenting how to integrate them, or from adding tests to Zappa for them, though.

Is there any value in having `@include` inside the query context? I can see a case where you'd like to consolidate your `@client` and `@shared` code in production (so that you can keep them coupled with server-side code in Zappa, but still benefit from a single download on the client), but I don't want to have to maintain this ugly hack if nobody is going to use it.

**Comment by scien** [comment]
k, connect-assets will definitely get the job done.  i have an example working. Originally, connect-assets wouldn't recompile when a dependency was updated, but I think that was a bug in snockets (https://github.com/TrevorBurnham/snockets/pull/22).  

here's a quick example of how connect-assets expects to be integrated

app.coffee

```
require('zappajs') 3000, ->
    assets = require 'connect-assets'
    @app.use assets {build: true, buildDir: 'public/bin', minifyBuilds: false, src: 'public'}
    @get '/' -> @render 'layout.coffee'
```

views/layout.coffee

```
html ->
    head ->
        text js 'app'
```

public/js/app.coffee

```
#= require 'dep'
```

public/js/dep.coffee

```
console.log 'hello world'
```

connect-assets will then replace js 'app' with script src="/js/app-83120f667e0cc1d77842c2227bfa5010.js"

a nice-to-have might be to instead do the following (being able to recognize the static url and respond)

views/layout.coffee

```
html ->
    head ->
        script src: '/static/app.js'
```

app.coffee

```
require('zappajs') 3000, ->
    @get '/static/app.js', ->
        assets = require('connect-assets').instance
        assets.options.helperContext.js 'app'
        @redirect '/' + assets.buildFilenames['js/app.coffee']
```

**Comment by shimaore** [comment]
Nice write-up :)  I'll update the documentation to add this.

I believe the reason

```
text js 'app'
```

is preferred over

```
script src: '/static/app.js'
```

is that the dynamic `src` tag contains a signature (hash) of the file to prevent a client browser or CDN from caching an obsolete version. I'm not sure what the best practice would be for a production environment.

[edit: removed question]

**Comment by scien** [comment]
agreed on the hash. i guess it'd be unclear how browsers would handle the redirect.  Probably best practice (and certainly more common from what i've seen) to do it the text js 'app' way.

buildDir can be placed within src without causing trouble.  src just defines the root path for where to look for files when you use "css" or "js".  so "text js 'app'" looked for the file public/js/app.coffee in my scenario.  snockets handles circular dependencies and ordering with dep-graph

**Comment by scien** [comment]
just following up here as I've switched my project to use connect-assets now (and now wish I had done it months ago). Might be good to add a require_tree example for javascript, and a stylus example for css.  also noting that you can't include coffeecup this way as it causes a syntax error.  should that issue be filed with coffee-script or uglifyjs?

text css 'app' 
app.styl

```
@import url(http://fonts.googleapis.com/css?family=Rancho)
@import url(http://fonts.googleapis.com/css?family=Muli)

@import 'vendor/bootstrap.css'
@import 'vendor/bootstrap-responsive.css'
@import 'vendor/font-awesome-2.0.3.css'

@import 'nib'
@import 'nib-ext'
...
```

test js 'app'
app.coffee

```
# Vendor
#= require 'vendor/jquery.js'
#= require 'vendor/underscore.js'
#= require 'vendor/backbone.js'
#= require 'vendor/backbone.queryparams.js'
#= require 'vendor/bootstrap.js'
#= require 'vendor/jquery.history.js'
#= require 'vendor/jquery.transit.js'
#= require 'vendor/highcharts.src.js'
#= require 'vendor/swfobject.js'

# Application
#= require 'init'
#= require_tree 'helpers'
#= require_tree 'templates'
#= require_tree 'views'
#= require 'router'
#= require 'main'
```
