### ISSUE TITLE
@title, etc. don't work anymore

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#24]
Express 3.x does not provide a way to retrieve the `options` set after it was processed by an engine; and it create a new, private copy of the one we pass to it.

Therefor well-documented Zappa features like `@title`, etc., don't work anymore in Express 3.x.

**Comment by shimaore** [comment]
Replace them with `@locals.title` ?

**Comment by shimaore** [comment]
That would also mean providing a default `locals` member in the options we send to `app.render`. Then doing `@locals.title = "My title"` and enabling the `default layout` should work (since options.locals gets merged directly into the root of the options sent to the template engine).

**Comment by shimaore** [comment]
I believe this is fixed, if the test is any indication.

**Comment by scien** [comment]
yup, looks good
