### ISSUE TITLE
@include doesn't work 

### ISSUE THREAD

**Issue by m9dfukc** [zappajs/zappajs#34]
calling `@include "./some.coffee"` 
results in `Cannot find module ... /.zappa-a7973752-2bc4-48ca-9294-2bdba413aea6/some.coffee`. 

looking at the source `require(path.join(context.root, p))` is used.
replacing it with `require(path.join(context.real_root, p))` resolves that error.

**Comment by scien** [comment]
hmm, that could break people's code and should probably be saved for a version bump. for the time being...

try @include '../some'

reference: https://github.com/scien/zappajs.com/blob/master/app/zappajs.coffee

**Comment by scien** [comment]
or maybe we could now as the current version on npm is still 0.3.10

**Comment by m9dfukc** [comment]
I can live with ../ but then the documentations needs to be corrected.

cheers

**Comment by shimaore** [comment]
Most definitely an oversight, `@include "./some.coffee"` should work.

Aside: Any reason `@root` should be exposed? It's not documented, and you can get to it doing `@app.get 'views'`.
I'm tempted to just make `real_root` and `root` private.

**Comment by shimaore** [comment]
Fixed in 0.4.7
