### ISSUE TITLE
favicon middleware won't load

### ISSUE THREAD

**Issue by scien** [zappajs/zappajs#35]
I'm seeing the same behavior I saw with socket.io when originally upgrading to 0.4.x.  server just hangs trying to load the resource.  You fixed socket.io with 0.4.5, what was the issue that time?

```
@app.use @express.favicon 'path_to_icon.ico'
```

**Comment by shimaore** [comment]
I tried: `test.coffee` →

```
require('zappajs') ->
  @app.use @express.favicon 'icon.ico'
  @get '/': 'bar'
```

`npm install zappajs@0.4`
`curl http://127.0.0.1:3000/favicon.ico`
`curl http://127.0.0.1:3000/`

and it doesn't block (also works with `@use` instead of `@app.use`).
Do you have something else in the zappa code that might cause this?

**Comment by scien** [comment]
Agh. Sorry.  The project I was running was still on 0.4.4.  All good.
