### ISSUE TITLE
Adding Express Validator

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#36]
Hey,

I'm thinking about adding [Express Validator](https://github.com/ctavan/express-validator) to Zappa. I wrote a [blog post](http://code.enginezombie.com/post/30087269669/a-bit-of-sugar-for-express-validator) about the sugar I'm using to make it nice.

Adding it straight into zappa will make two functions available `@assert` and `@sanitize`. I can also add support for socket.io.

Any thoughts on how the API should look like?

``` coffee
@get '/health', ->
  @on_error = @next # This is the error handler,
                                   # if asserting goes wrong, next()
                                   # is the default express error handler,
                                   # and @on_error should be equal to
                                   # next by default
  @pre =>
    @assert('param', 'Invalid Param').notEmpty()
  , =>
    # Validation Passed
    @response.json
      pid: process.pid
      memory: process.memoryUsage()
      uptime: process.uptime()
```

Also: the github fork this project link in Zappa's website is broken, and leads to the wrong repo.

**Comment by shimaore** [comment]
It should be possible to make it into your own zappajs plugin and publish it.

```
require('zappajs') ->
  @include require('zappajs-validator')
```

Plugin would look something like:

```
# zappajs-validator
@include = ->
  @use 'express-validator'
  @helper pre: (fn) ->
      error_handler = fn()
      errors = @req.validationErrors()
      if errors then error_handler(errors)
      else @next()
```

Unless I'm missing a piece where this needs to deal with Zappa internals?
