### ISSUE TITLE
Add an easy way to add things to context

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#37]
Again, this is pretty straightforward and I can do this, just want your go ahead before I plunge into the code.

We only need to add a `@context` var that will enable us to reference the context and add more functionality to it. This will improve the DSL quality of Zappa, as we can add `@assert` with this, and `@check` and `@create @job 'somejob', ['arg', 'u', 'ments']` without having to change zappa itself. I constantly find new ways to improve Zappa for my usage, like adding winston logging with `@error` and `@log` but there's no easy way to add them.

**Comment by shimaore** [comment]
Which context do you want to modify? There's a few of them in Zappa (they all are `@` when you are inside them), here are the main ones on the server side:

```
  require('zappajs') ->
    root_scope = this
    @get '/': ->
      request_handler_scope = this
    @on 'foo': ->
      socket_handler_scope = this
```

You can modify the `root_scope` at any time, e.g. with `@foo = -> do something`.
You can modify the `request_handler_scope` and `socket_handler_scope` with `@helper`. The data or code you add with `@helper` will be added to the scopes every time they are created.

**Comment by Radagaisus** [comment]
Wow, totally missed that. Thanks.
