### ISSUE TITLE
"Fork this Project" Link on Zappa's Website is broken (no image) and leads to the wrong repo

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#39]

**Comment by shimaore** [comment]
That would be on http://zappajs.org/ then, but that domain is controlled by @mauricemach and we have no way to change it.
@scien set up http://zappajs.com/ which describes zappajs 0.4.

**Comment by Radagaisus** [comment]
Thanks. Why did this project split up so much?

**Comment by shimaore** [comment]
@Radagaisus mauricemach (author of zappa and coffeekup among others) was last seen on github ten months ago. In April I decided to continue the work on zappa and created this community project. Same thing happened with coffeecup, the successor to coffeekup.
