### ISSUE TITLE
@all for Express

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#40]
``` coffee
@app.all '/api/v1/user/current/*', (req, res, next) ->
    if req.user then next()
    else res.end()
```

Just noticed there's no `@all` function. Should I write a pull request or is that intentional?

**Comment by shimaore** [comment]
I always thought it was intentional.
FWIW I just looked at the [Express 3.x doc](http://expressjs.com/api.html#application) and in the root (application) scope Zappa doesn't offer `@app.(all|locals|render|routes)`.
What do others think about adding `@all`?

**Comment by scien** [comment]
+1 for adding `@all`

**Comment by Radagaisus** [comment]
Looks good. What about `@param` for `app.param`?

**Comment by Radagaisus** [comment]
Example:

``` coffee
# Check if the user_id is a valid MongoDB ID
@param 'user_id', (req, res, next, user_id) ->
  if ~user_id.indexOf /^[0-9A-F]{24,24}$/i
    next("Invalid User ID")
  next()
```

**Comment by shimaore** [comment]
@Radagaisus please test `@param` (see documentation above)

**Comment by Radagaisus** [comment]
@shimaore I can't right now, I'm working with an older version of Zappa. I'll write tests in the weekend.

**Comment by Radagaisus** [comment]
Hey, I've added all the tests [here](https://github.com/Radagaisus/zappajs/commit/1a9f94d75f6c8c5100d1f92a69a89a4803c40e96). There's no need to test different HTTP methods, just different routes. If you want another test for different HTTP methods I'll add it.

**Comment by rchunduru** [comment]
When it is going to be available with npm?

**Comment by datashaman** [comment]
This can be closed.
