### ISSUE TITLE
Add `staticGzip` middleware

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#45]
Pull ee1a3dda5a63d0c108d34990b6923e343a995c94

**Comment by shimaore** [comment]
Now it needs tests.

**Comment by imzshh** [comment]
Good job:-)

**Comment by Radagaisus** [comment]
What about the Compress middleware? http://expressjs.com/api.html#compress

**Comment by imzshh** [comment]
`staticGzip` only compress static files, while the `compress` middleware compress all response content.

**Comment by Radagaisus** [comment]
[The docs](http://www.senchalabs.org/connect/compress.html) says you can pass a filter function for specific file types so we can use that. The reason I'm asking is that using compress means less code to maintain, less packages to depend on and zero tests to write :)

As an off topic: Unless it's a weekend project or a prototype I think nginx / apache should serve the static assets, not node.

**Comment by shimaore** [comment]
How about have our cake and eat it: we could leave the `staticGzip` option but make `gzippo` a soft dependency -- similar to what we already do for `jsdom`, `less`, etc.

**Comment by shimaore** [comment]
I seems that `gzippo` is dead (which makes sense given `compress`), and that `compress` (plus `staticCache` potentially) is the way to go.

I'll add a deprecation warning for `staticGzip` and I'm planning to remove that feature in a few versions.

**Comment by datashaman** [comment]
This is obsolete. staticGzip is deprecated. Can be closed.
