### ISSUE TITLE
Update Zappa's Synopsis

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#46]
Zappa has changed quite a bit, but the synopsis in the README is still the same. For example, there's no `@swap`:

``` coffee
@get '#/': ->
      @swap 'Ready to roll!'
```

(also: sorry for being busy this weekend, had an unexpected [terror attack](http://www.idfblog.com/2012/09/21/idf-thwarts-major-attack-on-israel-egypt-border/). @shimaore can I be a collaborator on the template project?)

**Comment by shimaore** [comment]
That's [Sammy's `@swap`](http://sammyjs.org/docs/api/0.7.1/all#Sammy.EventContext-swap).

-> Added you on zappajs-template.

**Comment by Radagaisus** [comment]
Woops. I'm absolutely not using anything related to the client side in Zappa, it's just our API server.

Thanks.
