### ISSUE TITLE
Is there a preferred zappajs-ist way to minify/concat coffee + less files now?

### ISSUE THREAD

**Issue by braco** [zappajs/zappajs#53]
It's not clear from the docs, but this is a pretty important piece that was obvious in the original zappa package. The connect-assets example seems pretty verbose.

For anyone searching, I guess it's usable with just: 

```
    @use require('connect-assets')()
```

**Comment by shimaore** [comment]
I guess we could add the one-liner as the first example with the proper caveats (using `assets` instead of `public`, etc.).
