### ISSUE TITLE
The link on http://zappajs.org/ points to the old repo

### ISSUE THREAD

**Issue by JohnMcLear** [zappajs/zappajs#54]
It points to http://github.com/mauricemach/zappa

**Comment by audreyt** [comment]
Well, http://zappajs.com/ is the new domain -- not sure we can do anything about the .org site until @mauricemach is back.

**Comment by shimaore** [comment]
Yup, we have no control over the domain, it auto-renewed this year so can't fix that.

**Comment by voltuer** [comment]
Just to point out, it'd be better if you linked to the new website on the top of the git repo, instead of the .github.com one which, by the way, has a start page that completely differs.
