### ISSUE TITLE
Array middleware problem

### ISSUE THREAD

**Issue by littlehaker** [zappajs/zappajs#55]
Consider stuff like:

``` coffeescript
common = [foo, bar, baz]
@get '/something', common, fn
```

I want to use array middleware like express, but this turn out to be an error:

``` javascript
TypeError: Object function (){
       this.next();
    },function (){
       this.next();
    },function (){
       this.next();
    } has no method 'apply'
```

**Comment by shimaore** [comment]
Currently you'd have to write:

```
common = [foo, bar, baz]
@get '/something', common..., fn
```

**Comment by shimaore** [comment]
As a side note, Express' [Router.route](https://github.com/visionmedia/express/blob/master/lib/router/index.js#L239) uses [flatten](https://github.com/visionmedia/express/blob/master/lib/utils.js#L55) to convert array arguments.

Is it worth copying `flatten` into the `zappajs` code, or is using the `...` notation OK? (Assuming we add an example in the documentation to make this explicit.)

**Comment by Radagaisus** [comment]
I think it's best we `flatten` stuff automatically for the developers. The pain should always be hidden inside the framework.
