### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by darvin** [zappajs/zappajs#58]
From my understanding it's impossible to do via connect/express middleware, and it could be nice addition to zappa.
Say,

```
@get '/': ->
  @render index: {foo: 'bar'}
```

And if request has header Accept-type: application/json, server will respond with JSON `{"foo":"bar"}` instead of view index rendered with `{foo:"bar"}`
Will it be accepted into upstream? If yes, I can do that

**Comment by Radagaisus** [comment]
Sounds cool. I like how Rails handle this. It allows for more fine-grained responses.

``` coffee
if err then @next err

@format
  json: =>
    @jsonp user.toJSON()
  html: =>
    @render index: user.toJSON()
```

Note that you can just implement this as a helper, no need to integrate this into zappa:

``` coffee
# Call fn if fn is a function
call = (fn, ctx, args...) -> if typeof fn is 'function' then fn.apply(ctx || this, args)

@helper format: (o) ->
  switch @request.get 'Content-Type'
      when 'application/json' then call o.json
      when 'text/html' then call o.html
```

**Comment by darvin** [comment]
oh, cool! thanks
