### ISSUE TITLE
zappajs / zappajs is ungooglebly!

### ISSUE THREAD

**Issue by darvin** [zappajs/zappajs#59]
Before I found this repo, I cloned first:
- https://github.com/mauricemach/zappa
- https://github.com/shimaore/zappajs

Let's do something about that, two of this repositories is really easier to find and seems deprecated.

**Comment by shimaore** [comment]
Ya, https://github.com/shimaore/zappajs was created during the interim; in retrospect zappajs should have pulled from mauricemach's. In any case I modified that repo to make it clear people should point here now.

Can't do much about mauricemach's or SEO trouble, though.

**Comment by scien** [comment]
zappajs.org expires on August 20, 2013.  When that happens, I'll pick it up and redirect to http://zappajs.github.com/zappajs/ like I'm doing with zappajs.com.

**Comment by scien** [comment]
just to note, it looks like we do have the top two results for "zappajs" on google.  We should add some keywords to also target words like node, framework, expressjs to try and draw more attention to the project.

We could maybe also add an application page like expressjs.com has.  I just launched http://ultramusicfestival.com/ earlier today (would love to hear people's thoughts/reactions).  I should have a lot more to share over the next few months as well.

Along that route, how about we change "X-Powered-By:Express" to "X-Powered-By:Zappa"
