### ISSUE TITLE
Including Files in Included files

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#60]
Hi,

So we got our main app:

``` coffee
# index.coffee
@include './config/initialize'
```

And then in `initialize` we also include other files

``` coffee
# initialize.coffee
@include = ->
    @include './initializers/express.coffee'
    @include './initializers/sockets.coffee'
```

Include will try to require `/initializers/express.coffee`, not `config/initializers/express.coffee`.

The reason is that `@include` uses `index.coffee` as the root:

``` coffee
context.root = path.dirname(module.parent.filename)
```

Instead of recalculating it whenever it tries to include stuff.

**Comment by shimaore** [comment]
Try the [@include require](http://zappajs.github.com/zappajs/docs/reference#id2) pattern:

```
# initialize.coffee
@include = ->
  @include require './initializers/express.coffee'
  @include require './initializers/sockets.coffee'
```

**Comment by Radagaisus** [comment]
woho!
