### ISSUE TITLE
Start Zappa without Binding to a Port

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#61]
``` coffee
app = context.app = express()
  if options.https?
    app.server = require('https').createServer options.https, app
  else
    app.server = require('http').createServer app
  io = if options.disable_io then null else context.io = socketio.listen(app.server)
```

Socket.io has the nice option of `disable_io` (that should be renamed, imho), but Express doesn't have this option. It would be nice if we had the same option for the Express. Currently express listens to a port no matter what:

``` coffee
if host
    app.server.listen port, host
  else
    app.server.listen port
```

It's important for testing. Getting an instance of Zappa without binding to a port helps making self-contained tests. Alternatively, we can offer a `.close()` function on Zappa that shuts down the listeners.

**Comment by shimaore** [comment]
You can use `zappa.app` to get a server that is not bound. (Look at [the code for `zappa.run`](https://github.com/zappajs/zappajs/blob/master/src/zappa.coffee#L656) for an example of how to use `zappa.app`.)

Also the test suite has instrumentation for testing with a bound server; it uses `request`, `jsdom` and `socket.io-client` to implement a browser-like environment. (That is a pretty clever package and can probably be used to test non-Zappa code, FWIW.) See e.g. [client.coffee](https://github.com/zappajs/zappajs/blob/master/tests/support/client.coffee).

**Comment by Radagaisus** [comment]
@shimaore I agree, it's a really nice test suite, and I wish it was a separately maintained package. But without docs I can't use it in professional projects. I'm using superagent with mocha to run my tests right now. I'm using `zappa.app` in the tests, but obviously Express still listens to a port.

For unit tests it's better if the server could be started from scratch on every test (just like `zappa port++` in Zappa's test suite). So either passing `port: false` or having a `.start()` and `.stop()` function will make the tests more versatile, and will help Zappa integrate more easily with other packages (cluster and forever comes to mind)

``` coffee
app     = require('./server')
express = app.app

it 'Returns a 200 OK JSON', (done) ->
  app.get '/random': ->
    @return hello: 'world!'

  agent(express)
    .get('/random')
    .end (err, res) ->

    expect(res.statusCode).toEqual 200
    expect(res.status).toEqual 200
    expect(res.type).toEqual 'application/json'
    expect(res.body).toEqual hello: 'world!'
    done()
```

**Comment by shimaore** [comment]
> I'm using zappa.app in the tests, but obviously Express still listens to a port.

Hmmmm.. It shouldn't. The `listen()` call is only in `zappa.run` (aka `zappa`). The following script will terminate immediately:

```
zappa = require 'zappajs'
zappa.app ->
  @get '/': 'hello'
```

The following on the other hand will not terminate, create a server on port 3000, and wait for connections:

```
zappa = require 'zappajs'
# assert zappa.run is zappa
zappa.run ->  
  @get '/': 'hello'
```

> For unit tests it's better if the server could be started from scratch on every test

In that case you need to get a new `app` every time. I tried to test your code, with changes along the lines of:

```
# issue61.coffee
zappajs = require 'zappajs'
superagent = require 'superagent'
mocha = require 'mocha'

it 'Returns a 200 OK JSON', (done) ->
  app = zappajs.app ->
    @get '/random': ->
      hello: 'world!'

  superagent.agent(app)
    .get('/random')
    .end (err,res) ->

       expect(res.statusCode).toEqual 200
       expect(res.status).toEqual 200
       expect(res.type).toEqual 'application/json'
       expect(res.body).toEqual hello: 'world!'
       done()
```

followed by `coffee -c issue61.coffee; mocha issue61.js` and it fails because superagent tries to connect to a real server.
I don't understand how `agent(express)` in your example code is supposed to work -- `superagent.agent` doesn't expect a parameter, so `agent` must be something else than `superagent.agent`.

**Comment by Radagaisus** [comment]
Oh, sorry, it's [supertest](https://github.com/visionmedia/supertest), not superagent. It expects an HTTP Server as a parameter.

This issue isn't about testing Zappa's internals, it's for people who want to test their Zappa apps, with all their helpers and routes. How can you achieve this without running Zappa?

**Comment by shimaore** [comment]
I got this to work:

```
supertest = require 'supertest'
zappajs = require 'zappajs'
mocha = require 'mocha'

describe 'GET /random', ->
  app = zappajs.app ->
    @get '/random': ->
      @send hello: 'world!'

  it 'returns a 200 OK JSON', (done) ->
    supertest(app.server)
      .get('/random')
      .expect('Content-Type', /json/)
      .expect('Content-Length', '23')
      .expect('{\n  "hello": "world!"\n}')
      .expect(200,done)
```

The trick you might have been missing was to use `app.server` instead of `app`?

**Comment by Radagaisus** [comment]
No :) Let's say I'm testing an **app I wrote**:

``` coffee
# server.coffee
module.exports = require('zappajs') 2222, ->
  @get '/health', ->
    @jsonp
      pid: process.pid
      memory: process.memoryUsage()
      uptime: process.uptime()
```

We need to give people a way to test their routes without binding to a port:

``` coffee
supertest = require 'supertest'
server    = require './server' # Zappa is now running!!
express = server.app
mocha = require 'mocha'

describe 'GET /health', ->

  it 'returns a 200 OK', (done) ->
    supertest(express)
      .get('/health')
      .expect('Content-Type', /json/)
      .expect(200,done)
```

**Comment by shimaore** [comment]
Ah! In that case you need to (re)write a little bit for testability :)

Remember how in [zappajs-template](https://github.com/zappajs/zappajs-template/tree/master/bin) we broke the _serve this application_ and the _here's the application_ pieces on purpose? For example you could do:

```
# server.coffee
module.exports = require('zappajs') 2222, ->
  @include './content.coffee'

# content.coffee
@include = ->
  @get '/health', ->
    @jsonp
      pid: process.pid
      memory: process.memoryUsage()
      uptime: process.uptime()
```

Then:

```
supertest = require 'supertest'
server    = require('zappajs').app ->
  @include './content.coffee'
express = server.app
mocha = require 'mocha'

describe 'GET /health', ->

  it 'returns a 200 OK', (done) ->
    supertest(express)
      .get('/health')
      .expect('Content-Type', /json/)
      .expect(200,done)
```

If you don't like `@include` you could probably even say:

```
app = require('zappajs').app ->
    @get '/health', ->
        ....

if require.main is module
  # Running as an application, start the server
  app.server.listen port
else
  # Only testing
  modules.export = app
```

**Comment by Radagaisus** [comment]
Nice. I think we should add this to the docs then, `How to Test Zappa Apps`.
