### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#63]
I want to follow-up a little bit on #58. 

This issue might be a case of missing middleware, not necessarily something we have to fix in Zappa.

It would be nice to have some capability to simplify handling of the [Accept\* request headers](http://tools.ietf.org/html/rfc2616#page-100): `Accept`, `Accept-Charset`, `Accept-Language`. Maybe also set the response headers (`Content-Type` -- includes charset --, `Content-Language`) automatically, and provide some tools for the application, as shown in #58.

Note: `Accept-Encoding` and `Content-Encoding` work at a different level (a middleware that handles `Accept-Encoding` might need to stream the response through a gzip pipe, for example). Supporting those would be a different project.

**Comment by scien** [comment]
for caching purposes, i would probably change the url if expecting different responses (ex: /item for html, /item.json for json.  or /en/blah for english, /es/blah for spanish). The helper mentioned in #58 is pretty convient though.

What are some examples where it's more common to use Content-Type, Accept-Language, etc over the two examples I just provided?

**Comment by Radagaisus** [comment]
Hi guys, straight from express' docs:

``` javascript
res.format({
  'text/plain': function(){
    res.send('hey');
  },

  'text/html': function(){
    res.send('hey');
  },

  'application/json': function(){
    res.send({ message: 'hey' });
  }
});
```

This doesn't look great, and we should probably wrap it in a nicer API, but it's baked in.

**Comment by shimaore** [comment]
Going through express → connect → send → mime it appears you can use any shortcut listed in https://github.com/broofa/node-mime/tree/master/types -- at least for common types the API looks fine to me. (But make your own opinion, look at the example in the commit above.)

**Comment by scien** [comment]
Might be worth using a full mime type in the example just so people know it's possible, or linking to the express docs (http://expressjs.com/api.html#res.format).

Other than that looks good to me.  Anything left to discuss here?
