### ISSUE TITLE
Jade extends and includes are not working

### ISSUE THREAD

**Issue by SimonDegraeve** [zappajs/zappajs#70]
The issue is caused because the jade compiler need a `filename` option.

From the jade documentation:

``` js
var jade = require('jade');

// Compile a function
var fn = jade.compile('string of jade', options);
fn(locals);
```
### Options
- `self`      Use a `self` namespace to hold the locals _(false by default)_
- `locals`    Local variable object
- `filename`  Used in exceptions, and required when using includes
- `debug`     Outputs tokens and function body generated
- `compiler`  Compiler to replace jade's default
- `compileDebug`  When `false` no debug instrumentation is compiled
- `pretty`    Add pretty-indentation whitespace to output _(false by default)_

so I changed this in lib/zappajs:

``` js
compile = function(template, data) {
      // Hack for jade
      if(data.settings['view engine'] == 'jade'){
        data.filename = data.settings['views'] + '/layout.jade'
      }
      // End Hack
      template = engine.compile(template, data);
      return function(data) {
        var k, v, _ref3;
        _ref3 = data.params;
        for (k in _ref3) {
          v = _ref3[k];
          if (typeof data[k] === 'undefined' && __indexOf.call(options.blacklist, k) < 0) {
            data[k] = v;
          }
        }
        return template(data);
      };
};
```

The problem is how can I get the view name dynamically instead of the hardcode "layout.jade"?

**Comment by shimaore** [comment]
Jade natively supports Express 3, there's no need to use `zappajs.adapter` for it.

If you need includes you should use [native Jade includes](https://github.com/visionmedia/jade#a13) instead of Zappa includes (which are backward-compatible, Express 2 includes).

As long as you have installed `zappajs` and `jade`, the following should work:

```
require('zappajs') ->
    @get '/': ->
      @render 'layout.jade'

    @view 'layout.jade': '''
      html
        include includes/head
        body
          h1 My Site
          p Welcome to my super amazing site.
          include includes/foot
    '''

    @view 'includes/head.jade': '''
      head
        script(src='/jquery.js')
    '''

    @view 'includes/foot.jade': '''
      p Thank you for using Jade with ZappaJS.
    '''
```

and it will output:

```
<html><head><script src="/jquery.js"></script></head><body><h1>My Site</h1><p>Welcome to my super amazing site.</p><p>Thank you for using Jade with ZappaJS.</p></body></html>
```

**Comment by SimonDegraeve** [comment]
Right, I removed that from my code, and it works! Nice.

```
blacklist = 'scope self locals filename debug compiler compileDebug inline'.split ' '
@engine jade: @zappa.adapter 'jade', blacklist
```
