### ISSUE TITLE
running coffee cuppa.coffee results in TypeError

### ISSUE THREAD

**Issue by hans-d** [zappajs/zappajs#71]
Trying out the first sample of the crash course, running `coffee cuppa.coffee` results in `TypeError: Object #<Object> has no method 'replace'`

Installled on a fresh (lubuntu 12.10 32 bit) environment:
- node.js - 0.8.21
- npm - 1.2.12
- cofffee-script - 1.6.0 (sudo npm install coffee-script -g)
- zappajs - 0.4.15 (sudo npm install zappajs)

Full stack trace:

```
at Module._compile (module.js:357:21)
at Object.exports.run (... coffee-script.js:124:45)
at compileScript (... coffee-script/command.js:166:290
at fs.stat.notSourcs.(anonymous function) (... coffeescript/command.js:141:18)
at fs.readFile (fs.js:297:15)
at Object.oncomplete (fs.js:297:15)
```

I'm quite new at node.js, zappajs etc.

**Comment by shimaore** [comment]
Can't reproduce with node.js 0.8.18 and coffee-script 1.6.1, I need to compile 0.8.21 to see if that might be the issue.

**Comment by shimaore** [comment]
OK, I get the same error with coffee-script 1.6.0 and node.js 0.8.18.
I'll confirm this still work with node.js 0.8.21, but would you mind re-installing coffee-script to get 1.6.1 and re-test? Thanks!

**Comment by shimaore** [comment]
Confirmed to run OK with node 0.8.21, coffee-script 1.6.1, zappajs 0.4.15.
So the culprit seems to be coffee-script 1.6.0.

**Comment by hans-d** [comment]
- coffee 1.6.1
- node.js 0.8.21

`no such file or directory '/home/hans/dev/zappa-test/node_modules/zappajs/vendor/sammy-0.7.4.min.js'`

I have cleaned out the zappa-test/node_modules and again `sudo npm installa zappajs``, same error

**Comment by hans-d** [comment]
downgrading to coffee-script@1.5.0 results also in the missing sammy file, upgrading to 1.6.0 has the TypeError again. Upgrade to 1.6.1 is complaining againg re the sammy file.

The /vendor folder only has jquery-1.8.3 and socket.io.min.
Removing node_modules and reinstalling zappajs does not help.

**Comment by shimaore** [comment]
That's because you tried to re-install zappajs while I was battling `npm` to do its job (obviously not your fault, just bad timing). Please try again, I was finally able to publish a working version (zappajs 0.4.18).

**Comment by hans-d** [comment]
Hi, thanks. Reinstalled zappajs (latest) version, now working !
