### ISSUE TITLE
/zappa/Zappa.js, /zappa/zappa.js, /zappa/jquery.js, etc. are not served.

### ISSUE THREAD

**Issue by danscan** [zappajs/zappajs#75]
When I try to use zappa's client-side scripts, they aren't served.

**Comment by danscan** [comment]
I discovered my issue!  I didn't think I needed to explicitly:

``` coffeescript
@use 'zappa' 
```

I didn't see anything in the docs about that, and many of the examples, including the synopsis show an app using zappa/Zappa-simple.js without `@use 'zappa'` anywhere.

**Comment by shimaore** [comment]
The scripts will be served if you `@use 'zappa'` _or_ if you use any features that require them -- this is why the examples normally don't have `@use 'zappa'`.
