### ISSUE TITLE
Zappa module, exporting "zappa_fs" 

### ISSUE THREAD

**Issue by Hypee** [zappajs/zappajs#76]
Hi there,

Inline views are not supported by Express-partials / Zappa-partials module, 
would you mind to add an export to Zappa to be able to tweak the partials module ?

``` coffeescript
module.exports.zappa_fs = zappa_fs;
```

Regards,

Pascal

**Comment by shimaore** [comment]
That's weird because the tests contain things like:

```
  @use 'partials'
  @get '/': ->
    @render 'index', foo: 'bar', layout: 'bart'

  @view index: -> h2 "My inline template says foo=#{@foo}"

  @view bart: ->
    doctype 5
    html ->
      head ->
        title 'inline layout'
      body @body
```

which specifically test for inline views and layout.

**Comment by Hypee** [comment]
Are you sure layouts are also managed by the "Express/Zappajs-partials" module ?
If I comment the @use 'partials', the code is still working.

I will double check & post a non working "partial" code.

**Comment by Hypee** [comment]
Ok, well I should have written a test code before opening an issue, partials are working with inline views.

This code works : 

``` coffeescript
require('zappajs') ->

  @use 'partials'

  @get '/partial': ->
    @render 'skeleton', layout: no

  @view skeleton: ->
    doctype 5
    html ->
      head ->
        title 'partial test'
      body ->
        @partial "body"

  @view 'body': ->
    h1 "Body there"
```

I've started to tweak the Zappa-partials modules because this one doesn't work ( "_" in view name not accepted) :

``` coffeescript
require('zappajs') ->

  @use 'partials'

  @get '/partial': ->
    @render 'skeleton', layout: no

  @view skeleton: ->
    doctype 5
    html ->
      head ->
        title 'partial test'
      body ->
        @partial "partial_body"

  @view 'partial_body': ->
    h1 "Body there"
```

I'm still a bit stuck with my customized "partials module" (I've also added few functionalities that are specific to my framework).

I will make a fork of Zappajs & add what I need instead of bothering you.

Thanks for your help !

**Comment by Hypee** [comment]
Another problem I had with current Zappajs-partials module, the context is not sent to partials :

``` coffeescript
require('zappajs') ->

  @use 'partials'

  @get '/': ->
    @render 'skeleton', layout: no, foo: 'bar'

  @view skeleton: ->
    doctype 5
    html ->
      head ->
        title 'partial test'
      body ->
        p "**#{@foo}**" # bar
        @partial "body"

  @view 'body': ->
    h1 "Body there"
    p "**#{@foo}**" # undefined
```

**Comment by shimaore** [comment]
Would

```
@partial "body", @
```

work?

Or maybe this is something for `@locals` ?

_As an aside... I've been longing for an async coffeecup (with `include`) for some time. Express 3 has been out for some time and gradus/coffeecup#27 has been opened for a year but no traction there. I'd love to especially get rid of partials for core zappa (i.e. coffeecup) so that we're closer to Express 3. (It took me a while to admit moving to async templating was the Right Thing To Do, though.)_
