### ISSUE TITLE
@enable 'databag' fails

### ISSUE THREAD

**Issue by noc7c9** [zappajs/zappajs#77]
Fails with `ReferenceError: data is not defined`

I believe the problem is on [zappa.coffee#L498](https://github.com/zappajs/zappajs/blob/master/src/zappa.coffee#L498)
I believe `opts.params = data` should be `opts.params = ctx.data`

Would've fixed it myself but didn't feel like forking and making a pull request for such a small change and I don't actually plan on using databag so...

**Comment by shimaore** [comment]
Thanks for the report and fix.

On the other hand this confirms `databag` belongs to the list of "nobody uses this, let's get rid of it" zappa non-features.

**Comment by shimaore** [comment]
Databag is history with 1.x, so let's close this.
