### ISSUE TITLE
Configuring socket.io during app initialization

### ISSUE THREAD

**Issue by noc7c9** [zappajs/zappajs#78]
I'm using a custom logger for my app and I would like to replace the internal logger used by socket.io for consistency. However using `io.set` would be too late as `socket.io` starts logging as soon as the `listen` method is called.

I need to pass a configuration object onto the `listen` method.

``` js
var socket = require('socket.io').listen(80, {
  // options can go here
});
```

Perhaps zappa could support this with an api like this?

``` coffee
options =
  socketio:
    logger:
      debug: logger.debug
      info: logger.info
      warn: logger.warn
      error: logger.error
zappa.run options, -> ...
```

---

On another note, in the [api reference](http://zappajs.github.com/zappajs/docs/reference) it says
`zappa.app [locals,] function`
This is wrong, `zappa.app` doesn't take a `locals` object, it should really be
`zappa.app function [, options]`

**Comment by shimaore** [comment]
Regarding socket.io options, I actually have this in my local repo, but I didn't push it because I was trying to get it in for `path` which isn't available in socket.io 0.9. But I'll be happy to push it now!

You're right regarding the options to `zappa.app`, the doc needs to be updated.

**Comment by shimaore** [comment]
7d9078d11f21f0a3b0c028740749f714b8b3372e for option `io`

**Comment by noc7c9** [comment]
Thanks for the quick fix.

Also shouldn't
`zappa.app function [, options]`
instead be
`zappa.app [options,] function`?

**Comment by shimaore** [comment]
> Also shouldn't
> `zappa.app function [, options]`
> instead be
> `zappa.app [options,] function`?

I wondered about that. I hesitated between backward compatibility and API consistency.

Looking back I think we can have our cake and eat it, one is a function, the other an object.
