### ISSUE TITLE
Backporting maurimach/zappa's pull requests

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#8]
Here's the list of pull requests from mauricemach/zappa and their current status wrt zappajs/zappajs
# Applied But Incomplete
- mauricemach/zappa#123 applied, needs tests + doc
- mauricemach/zappa#103 needs tests + doc
- mauricemach/zappa#104 in #11
- mauricemach/zappa#118
# Applied, Can Close
- mauricemach/zappa#116 applied (jQuery 1.7.2, sammy 0.7.1)
- mauricemach/zappa#122
- mauricemach/zappa#100
- mauricemach/zappa#81 in #16
- mauricemach/zappa#117 applied
- mauricemach/zappa#99 -- all extra `context` or `databag` arguments have now been remove from zappajs 0.4
- mauricemach/zappa#90 -- fixed in #32
- mauricemach/zappa#124 looks OK, needs tests + doc
# Not Needed
- mauricemach/zappa#95 is pretty extensive, needs to be tested (and maybe updated), adds dependency, but would solve mauricemach/zappa#79 -- and not needed anymore, `connect-assets` does the job (add jquery, sammy, and Zappa's `client.js` to the assets to get a single-file download, or use the recent `/zappa/Zappajs` download).
- mauricemach/zappa#102 needs some minor work -- not needed, `databag` is no longer supported that way

**Comment by shimaore** [comment]
Regarding mauricemach/zappa#90, [this solution](http://stackoverflow.com/questions/4753957/socket-io-authentication/4782933#4782933) looks like a good approach. However it probably needs to be deployed in a middleware, not in Zappa.

**Comment by scien** [comment]
Is the goal here to support when the app server and socket server are together or separated?  together seems much simpler as you just need to share a MemoryStore and a map to lookup sockets by their id. so is the goal is to allow the following...

```
require('zappajs') 3000, ->
  @get '/': (req, res) ->
    res.send 'hello world'
  @get '/do_something': (req, res) ->
    @emit 'shout', {message: 'you did something!'}
    res.end()

  @client '/index.js': ->
    @connect()
    @on shout: ->
      alert "#{@data.message}!!!!!"
    $.get '/do_something' 
```

**Comment by shimaore** [comment]
OK, at this time all backports from mauricemach/zappa have been applied or won't be included.

Only remaining things is to add some tests for those indicated, any volunteers? :)

**Comment by shimaore** [comment]
Out of the four issues marked "incomplete", two have to do with layout, which was removed in 1.x, while the other remaining two does have proper tests or demos.
