### ISSUE TITLE
Get build to work on Travis

### ISSUE THREAD

**Issue by shimaore** [zappajs/zappajs#85]
Travis doesn't offer `cake` by default, need to update the build process e.g. along the lines of http://relistan.com/coffeescript-testing-on-travis-ci/

**Comment by Radagaisus** [comment]
``` yml
# travis.yml
before_script:
    - "npm i -g coffee-script"
```

should take care of this.

**Comment by shimaore** [comment]
I don't see the `before_script` in Travis's logs, but anyhow the issue is apparently with Travis not being able to download the NPM packages, not with the ZappaJS code. I don't think I can fix that :)

**Comment by datashaman** [comment]
This can be closed.
